spring:
  profiles:
    active: dev
    datasource:
      url: jdbc:mysql://localhost:3306/esl_two_tata?useUnicode=true&amp;characterEncoding=utf8"
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.ontime.demo.bean
  mapperLocations: classpath:mapper/*.xml